export const CATEGORIES_ACTION_TYPE = {
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORY_FAILED: "FETECH_CATEGORIES_FAILED",
};
